export type Skill = {
  slug: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  author: string;
  authorHandle: string;
  version: string;
  downloads: number;
  stars: number;
  updatedAt: string;
  createdAt: string;
  icon: string;
  accent: string;
  verified: boolean;
  featured?: boolean;
  files: { name: string; type: "file" | "folder"; size?: string }[];
  readme: string[];
  changelog: { version: string; date: string; note: string }[];
};

export const categories = [
  { name: "全部技能", count: 128 },
  { name: "代码质量", count: 32 },
  { name: "开发效率", count: 26 },
  { name: "文档生成", count: 18 },
  { name: "测试", count: 16 },
  { name: "安全", count: 14 },
  { name: "DevOps", count: 12 },
  { name: "前端", count: 10 },
];

export const skills: Skill[] = [
  {
    slug: "react-performance-audit",
    name: "React 性能检查",
    description: "定位 React 应用中的渲染瓶颈、状态设计问题与不必要的重渲染。",
    category: "前端",
    tags: ["React", "性能", "前端"],
    author: "Lin Chen",
    authorHandle: "linchen",
    version: "1.4.0",
    downloads: 18240,
    stars: 482,
    updatedAt: "2 天前",
    createdAt: "2025-11-06",
    icon: "⚡",
    accent: "indigo",
    verified: true,
    featured: true,
    files: [
      { name: "SKILL.md", type: "file", size: "6.4 KB" },
      { name: "references", type: "folder" },
      { name: "performance-checklist.md", type: "file", size: "3.1 KB" },
      { name: "examples", type: "folder" },
    ],
    readme: [
      "这个 Skill 会像一位资深前端工程师一样审查 React 代码，优先寻找真实影响用户体验的问题。",
      "它会检查组件边界、状态提升、memo 使用、列表渲染、网络请求和 Bundle 体积，并给出带优先级的修改建议。",
      "适合在提交 Pull Request 前运行，也适合排查页面交互变慢、首屏加载过重等问题。",
    ],
    changelog: [
      { version: "1.4.0", date: "2026-03-18", note: "新增 React 19 Actions 与 use API 检查规则。" },
      { version: "1.3.0", date: "2026-01-22", note: "补充虚拟列表和图片加载优化建议。" },
      { version: "1.0.0", date: "2025-11-06", note: "首次发布。" },
    ],
  },
  {
    slug: "code-review-assistant",
    name: "代码审查助手",
    description: "从正确性、可维护性和风险三个维度审查 Pull Request，输出可执行反馈。",
    category: "代码质量",
    tags: ["Review", "GitHub", "工程化"],
    author: "Mia Zhang",
    authorHandle: "miazhang",
    version: "2.1.0",
    downloads: 24300,
    stars: 731,
    updatedAt: "5 天前",
    createdAt: "2025-09-14",
    icon: "◎",
    accent: "violet",
    verified: true,
    featured: true,
    files: [
      { name: "SKILL.md", type: "file", size: "8.8 KB" },
      { name: "review-rubric.md", type: "file", size: "5.2 KB" },
      { name: "references", type: "folder" },
    ],
    readme: [
      "把零散的 Review 经验整理成一套可复用的审查流程，帮助团队更快发现高影响问题。",
      "默认按照阻塞发布的问题、潜在回归、可维护性建议三个层级组织反馈。",
      "支持传入 Diff、单个文件或完整 PR 上下文，不会为了风格偏好制造噪音。",
    ],
    changelog: [
      { version: "2.1.0", date: "2026-03-15", note: "新增变更风险评分和测试缺口提示。" },
      { version: "2.0.0", date: "2026-02-01", note: "重写审查工作流，降低低价值反馈。" },
    ],
  },
  {
    slug: "unit-test-generator",
    name: "单元测试生成器",
    description: "分析函数边界与异常路径，生成贴合现有测试框架的单元测试。",
    category: "测试",
    tags: ["Jest", "Vitest", "测试"],
    author: "Yuki Wang",
    authorHandle: "yuki-w",
    version: "1.2.3",
    downloads: 15680,
    stars: 398,
    updatedAt: "1 周前",
    createdAt: "2025-10-02",
    icon: "✓",
    accent: "emerald",
    verified: true,
    files: [
      { name: "SKILL.md", type: "file", size: "5.7 KB" },
      { name: "test-patterns", type: "folder" },
      { name: "fixtures.md", type: "file", size: "2.8 KB" },
    ],
    readme: [
      "根据项目已有的测试风格生成测试，而不是套用一份脱离上下文的模板。",
      "重点覆盖边界值、错误处理、异步状态和依赖注入等经常被遗漏的路径。",
      "在输出测试代码前，会先解释测试意图和未覆盖的风险。",
    ],
    changelog: [
      { version: "1.2.3", date: "2026-03-10", note: "修复参数化测试的 TypeScript 类型推断。" },
      { version: "1.2.0", date: "2026-02-17", note: "支持 Vitest 项目识别。" },
    ],
  },
  {
    slug: "sql-migration-checker",
    name: "SQL 迁移检查",
    description: "检查数据库迁移的锁表风险、兼容性、回滚策略与大表变更影响。",
    category: "安全",
    tags: ["SQL", "数据库", "迁移"],
    author: "Kai Liu",
    authorHandle: "kailiu",
    version: "1.0.8",
    downloads: 9840,
    stars: 251,
    updatedAt: "3 天前",
    createdAt: "2025-12-11",
    icon: "▦",
    accent: "amber",
    verified: false,
    files: [
      { name: "SKILL.md", type: "file", size: "7.2 KB" },
      { name: "database-guides", type: "folder" },
      { name: "risk-matrix.md", type: "file", size: "4.0 KB" },
    ],
    readme: [
      "在执行迁移前，识别可能造成长时间锁表、全表扫描和线上不兼容的操作。",
      "覆盖 PostgreSQL、MySQL 和常见 ORM 生成的迁移文件。",
      "输出风险等级、影响范围和推荐的分阶段迁移方案。",
    ],
    changelog: [
      { version: "1.0.8", date: "2026-03-16", note: "新增 PostgreSQL ENUM 变更检查。" },
      { version: "1.0.0", date: "2025-12-11", note: "首次发布。" },
    ],
  },
  {
    slug: "api-doc-generator",
    name: "API 文档生成器",
    description: "从路由、类型和示例中整理出清晰、可交付的 API 文档。",
    category: "文档生成",
    tags: ["API", "OpenAPI", "文档"],
    author: "Nora Xu",
    authorHandle: "noraxu",
    version: "1.8.2",
    downloads: 12100,
    stars: 306,
    updatedAt: "4 天前",
    createdAt: "2025-08-20",
    icon: "≡",
    accent: "sky",
    verified: true,
    files: [
      { name: "SKILL.md", type: "file", size: "5.9 KB" },
      { name: "openapi-template.yaml", type: "file", size: "6.1 KB" },
      { name: "references", type: "folder" },
    ],
    readme: [
      "从后端代码和请求示例中提取 API 的真实行为，生成前端和外部使用者都能读懂的文档。",
      "会主动标注缺失的错误响应、鉴权要求、分页约定和字段示例。",
      "支持 Markdown 和 OpenAPI 两种输出方向。",
    ],
    changelog: [
      { version: "1.8.2", date: "2026-03-14", note: "优化嵌套响应类型的字段说明。" },
      { version: "1.8.0", date: "2026-02-09", note: "增加 OpenAPI 3.1 输出模式。" },
    ],
  },
  {
    slug: "docker-optimizer",
    name: "Docker 优化助手",
    description: "分析 Dockerfile 与镜像构建流程，减少体积、构建时间和运行时风险。",
    category: "DevOps",
    tags: ["Docker", "CI/CD", "部署"],
    author: "Owen He",
    authorHandle: "owenhe",
    version: "1.3.1",
    downloads: 8750,
    stars: 219,
    updatedAt: "6 天前",
    createdAt: "2025-07-26",
    icon: "◇",
    accent: "cyan",
    verified: false,
    files: [
      { name: "SKILL.md", type: "file", size: "6.0 KB" },
      { name: "dockerfile-patterns.md", type: "file", size: "4.8 KB" },
      { name: "ci-examples", type: "folder" },
    ],
    readme: [
      "围绕镜像体积、构建缓存、权限和可复现性给出具体优化建议。",
      "会检查多阶段构建、基础镜像选择、依赖安装和敏感信息泄露。",
      "适合接入 CI，在合并前持续检查容器构建质量。",
    ],
    changelog: [
      { version: "1.3.1", date: "2026-03-12", note: "新增 Node.js pnpm 缓存规则。" },
      { version: "1.3.0", date: "2026-01-30", note: "支持 distroless 镜像建议。" },
    ],
  },
  {
    slug: "accessibility-audit",
    name: "前端可访问性检查",
    description: "检查语义化、键盘操作、对比度和屏幕阅读器体验，提升产品可用性。",
    category: "前端",
    tags: ["a11y", "WCAG", "UI"],
    author: "Sora Lin",
    authorHandle: "soralin",
    version: "1.1.4",
    downloads: 7320,
    stars: 188,
    updatedAt: "2 周前",
    createdAt: "2025-11-24",
    icon: "◌",
    accent: "rose",
    verified: true,
    files: [
      { name: "SKILL.md", type: "file", size: "7.5 KB" },
      { name: "wcag-quick-reference.md", type: "file", size: "7.9 KB" },
      { name: "aria-patterns", type: "folder" },
    ],
    readme: [
      "从真实用户操作路径出发，审查页面能否被键盘、屏幕阅读器和低视力用户使用。",
      "不会只列出规则，而是给出贴合当前 DOM 结构的修复示例。",
      "支持 React、Vue 和原生 HTML 项目。",
    ],
    changelog: [
      { version: "1.1.4", date: "2026-03-03", note: "补充对话框与菜单的焦点管理检查。" },
      { version: "1.1.0", date: "2026-01-12", note: "增加 WCAG 2.2 AA 映射。" },
    ],
  },
  {
    slug: "security-vulnerability-scanner",
    name: "安全漏洞检查",
    description: "扫描依赖、鉴权、输入处理和敏感信息，帮助提前发现常见安全问题。",
    category: "安全",
    tags: ["安全", "依赖", "OWASP"],
    author: "Evan Zhou",
    authorHandle: "evanzhou",
    version: "2.0.1",
    downloads: 20140,
    stars: 654,
    updatedAt: "昨天",
    createdAt: "2025-06-30",
    icon: "△",
    accent: "red",
    verified: true,
    featured: true,
    files: [
      { name: "SKILL.md", type: "file", size: "9.2 KB" },
      { name: "owasp-checklist.md", type: "file", size: "5.4 KB" },
      { name: "security-patterns", type: "folder" },
    ],
    readme: [
      "用可操作的检查清单审查应用中的高频安全风险，适合在代码变更和发布前使用。",
      "覆盖注入、越权、密钥泄露、依赖漏洞、SSRF 和不安全的默认配置。",
      "输出证据、影响和修复优先级，不提供未经验证的安全结论。",
    ],
    changelog: [
      { version: "2.0.1", date: "2026-03-19", note: "更新依赖漏洞检查格式，增加供应链风险提示。" },
      { version: "2.0.0", date: "2026-02-14", note: "重构为按风险等级分组的输出。" },
    ],
  },
  {
    slug: "readme-generator",
    name: "README 生成器",
    description: "根据项目结构和脚本生成准确、易维护的 README 初稿。",
    category: "文档生成",
    tags: ["README", "文档", "开源"],
    author: "Jing Guo",
    authorHandle: "jingguo",
    version: "1.0.6",
    downloads: 6450,
    stars: 142,
    updatedAt: "3 周前",
    createdAt: "2025-12-03",
    icon: "#",
    accent: "slate",
    verified: false,
    files: [
      { name: "SKILL.md", type: "file", size: "4.2 KB" },
      { name: "readme-outline.md", type: "file", size: "2.3 KB" },
      { name: "templates", type: "folder" },
    ],
    readme: [
      "从 package scripts、目录结构和现有配置中提取项目事实，生成可以直接继续编辑的 README。",
      "默认包含安装、开发、测试、部署和贡献指南，并会标记无法确认的内容。",
      "适合新项目初始化，也适合长期维护的内部工具。",
    ],
    changelog: [
      { version: "1.0.6", date: "2026-02-28", note: "新增 monorepo 项目结构识别。" },
      { version: "1.0.0", date: "2025-12-03", note: "首次发布。" },
    ],
  },
  {
    slug: "git-commit-helper",
    name: "Git Commit 助手",
    description: "理解代码变更并生成清晰、符合团队约定的 Commit 信息。",
    category: "开发效率",
    tags: ["Git", "Commit", "协作"],
    author: "Kai Liu",
    authorHandle: "kailiu",
    version: "1.5.2",
    downloads: 11020,
    stars: 287,
    updatedAt: "1 周前",
    createdAt: "2025-08-08",
    icon: "⌘",
    accent: "orange",
    verified: true,
    files: [
      { name: "SKILL.md", type: "file", size: "4.8 KB" },
      { name: "conventional-commits.md", type: "file", size: "3.3 KB" },
      { name: "examples", type: "folder" },
    ],
    readme: [
      "先阅读 Diff 和上下文，再生成能让协作者快速理解意图的提交信息。",
      "支持 Conventional Commits，也支持按团队现有格式输出。",
      "对于混合变更，会建议拆分提交，而不是把多个目的压进一句话。",
    ],
    changelog: [
      { version: "1.5.2", date: "2026-03-08", note: "增加中文 Commit 标题风格选项。" },
      { version: "1.5.0", date: "2026-01-25", note: "支持从 staged Diff 推断 scope。" },
    ],
  },
  {
    slug: "nextjs-best-practices",
    name: "Next.js 最佳实践",
    description: "围绕 App Router、缓存、渲染边界和路由组织给出 Next.js 建议。",
    category: "开发效率",
    tags: ["Next.js", "React", "架构"],
    author: "Mia Zhang",
    authorHandle: "miazhang",
    version: "2.3.0",
    downloads: 17380,
    stars: 512,
    updatedAt: "4 天前",
    createdAt: "2025-10-18",
    icon: "N",
    accent: "black",
    verified: true,
    featured: true,
    files: [
      { name: "SKILL.md", type: "file", size: "8.1 KB" },
      { name: "app-router-guide.md", type: "file", size: "6.7 KB" },
      { name: "patterns", type: "folder" },
    ],
    readme: [
      "针对正在使用 Next.js App Router 的项目，帮助 Agent 在合适的边界做出更稳妥的实现。",
      "涵盖 Server Components、Server Actions、缓存、错误边界和 Metadata。",
      "会优先尊重已有代码结构，只有在收益明确时才建议引入新的抽象。",
    ],
    changelog: [
      { version: "2.3.0", date: "2026-03-17", note: "增加 Cache Components 和 Partial Prerendering 说明。" },
      { version: "2.2.0", date: "2026-02-06", note: "补充 Metadata 与 OG 图片检查。" },
    ],
  },
  {
    slug: "python-refactor-helper",
    name: "Python 重构助手",
    description: "在保持行为不变的前提下，拆分复杂逻辑并改善 Python 代码的可读性。",
    category: "代码质量",
    tags: ["Python", "重构", "类型"],
    author: "Rui Sun",
    authorHandle: "ruisun",
    version: "1.1.0",
    downloads: 8290,
    stars: 204,
    updatedAt: "2 周前",
    createdAt: "2025-09-29",
    icon: "Py",
    accent: "blue",
    verified: false,
    files: [
      { name: "SKILL.md", type: "file", size: "6.8 KB" },
      { name: "refactor-recipes.md", type: "file", size: "4.6 KB" },
      { name: "examples", type: "folder" },
    ],
    readme: [
      "从函数长度、职责边界、重复逻辑和类型表达等方面识别值得重构的代码。",
      "先建立行为保护，再逐步重构，避免为了追求形式而改变业务语义。",
      "兼容 Django、FastAPI 和常见数据处理脚本。",
    ],
    changelog: [
      { version: "1.1.0", date: "2026-03-01", note: "增加 async/await 重构模式。" },
      { version: "1.0.0", date: "2025-09-29", note: "首次发布。" },
    ],
  },
  {
    slug: "commit-message-linter",
    name: "提交信息规范器",
    description: "统一团队 Commit、分支和 PR 标题格式，让变更历史更容易检索。",
    category: "开发效率",
    tags: ["Git", "规范", "团队"],
    author: "Noah Fang",
    authorHandle: "noahfang",
    version: "0.9.5",
    downloads: 4380,
    stars: 98,
    updatedAt: "1 个月前",
    createdAt: "2026-01-05",
    icon: "↳",
    accent: "teal",
    verified: false,
    files: [
      { name: "SKILL.md", type: "file", size: "3.9 KB" },
      { name: "team-conventions.md", type: "file", size: "2.1 KB" },
    ],
    readme: [
      "根据团队约定检查提交信息和 PR 标题，并在发现不一致时给出最小修改建议。",
      "可以读取仓库中的配置文件，适配不同团队的 scope、type 和语言偏好。",
      "适合与 Git Commit 助手组合使用。",
    ],
    changelog: [
      { version: "0.9.5", date: "2026-02-11", note: "支持从 CONTRIBUTING.md 读取约定。" },
    ],
  },
];

export const featuredSkills = skills.filter((skill) => skill.featured);

export function getSkill(slug: string) {
  return skills.find((skill) => skill.slug === slug);
}
